from django.db import models


class Player(models.Model):
    atp_id = models.IntegerField()
    country = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    hand = models.CharField(max_length=1)
    ranking = models.IntegerField(null=True, blank=True)
    ranking_points = models.IntegerField(null=True, blank=True)
    elo = models.IntegerField(default=1500)
    elo_grass = models.IntegerField(default=1500)
    elo_clay = models.IntegerField(default=1500)
    elo_hard = models.IntegerField(default=1500)


class Tourney(models.Model):
    tourney_id = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    start_date = models.DateField(null=True, blank=True)
    surface = models.CharField(max_length=30)
    draw_size = models.IntegerField(null=True, blank=True)
    tourney_level = models.CharField(max_length=6, null=True, blank=True)


class Match(models.Model):
    w_player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='w_match')
    l_player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name='l_match')
    tourney = models.ForeignKey(Tourney, on_delete=models.CASCADE)
    score = models.CharField(max_length=120, null=True, blank=True)
    best_of	= models.IntegerField(null=True, blank=True)
    match_num = models.IntegerField(null=True, blank=True)
    round = models.CharField(max_length=6, null=True, blank=True)
    minutes	= models.IntegerField(null=True, blank=True)
    w_ace = models.IntegerField(null=True, blank=True)
    w_df = models.IntegerField(null=True, blank=True)
    w_svpt = models.IntegerField(null=True, blank=True)
    w_1stIn	= models.IntegerField(null=True, blank=True)
    w_1stWon = models.IntegerField(null=True, blank=True)
    w_2ndWon = models.IntegerField(null=True, blank=True)
    w_SvGms	= models.IntegerField(null=True, blank=True)
    w_bpSaved = models.IntegerField(null=True, blank=True)
    w_bpFaced = models.IntegerField(null=True, blank=True)
    l_ace = models.IntegerField(null=True, blank=True)
    l_df = models.IntegerField(null=True, blank=True)
    l_svpt = models.IntegerField(null=True, blank=True)
    l_1stIn = models.IntegerField(null=True, blank=True)
    l_1stWon = models.IntegerField(null=True, blank=True)
    l_2ndWon = models.IntegerField(null=True, blank=True)
    l_SvGms = models.IntegerField(null=True, blank=True)
    l_bpSaved = models.IntegerField(null=True, blank=True)
    l_bpFaced = models.IntegerField(null=True, blank=True)
    winner_rank = models.IntegerField(null=True, blank=True)
    winner_rank_points = models.IntegerField(null=True, blank=True)
    loser_rank = models.IntegerField(null=True, blank=True)
    loser_rank_points = models.IntegerField(null=True, blank=True)
    w_elo = models.IntegerField(null=True, blank=True)
    l_elo = models.IntegerField(null=True, blank=True)
    w_elo_ts = models.IntegerField(null=True, blank=True)
    l_elo_ts = models.IntegerField(null=True, blank=True)
