# Generated by Django 3.1.7 on 2021-04-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atp_id', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('hand', models.CharField(max_length=1)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('ranking_points', models.IntegerField(blank=True, null=True)),
                ('elo', models.IntegerField(default=1500)),
                ('elo_grass', models.IntegerField(default=1500)),
                ('elo_clay', models.IntegerField(default=1500)),
                ('elo_hard', models.IntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Tourney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourney_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('surface', models.CharField(max_length=30)),
                ('draw_size', models.IntegerField(blank=True, null=True)),
                ('tourney_level', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(blank=True, max_length=120, null=True)),
                ('best_of', models.IntegerField(blank=True, null=True)),
                ('match_num', models.IntegerField(blank=True, null=True)),
                ('round', models.CharField(blank=True, max_length=6, null=True)),
                ('minutes', models.IntegerField(blank=True, null=True)),
                ('w_ace', models.IntegerField(blank=True, null=True)),
                ('w_df', models.IntegerField(blank=True, null=True)),
                ('w_svpt', models.IntegerField(blank=True, null=True)),
                ('w_1stIn', models.IntegerField(blank=True, null=True)),
                ('w_1stWon', models.IntegerField(blank=True, null=True)),
                ('w_2ndWon', models.IntegerField(blank=True, null=True)),
                ('w_SvGms', models.IntegerField(blank=True, null=True)),
                ('w_bpSaved', models.IntegerField(blank=True, null=True)),
                ('w_bpFaced', models.IntegerField(blank=True, null=True)),
                ('l_ace', models.IntegerField(blank=True, null=True)),
                ('l_df', models.IntegerField(blank=True, null=True)),
                ('l_svpt', models.IntegerField(blank=True, null=True)),
                ('l_1stIn', models.IntegerField(blank=True, null=True)),
                ('l_1stWon', models.IntegerField(blank=True, null=True)),
                ('l_2ndWon', models.IntegerField(blank=True, null=True)),
                ('l_SvGms', models.IntegerField(blank=True, null=True)),
                ('l_bpSaved', models.IntegerField(blank=True, null=True)),
                ('l_bpFaced', models.IntegerField(blank=True, null=True)),
                ('winner_rank', models.IntegerField(blank=True, null=True)),
                ('winner_rank_points', models.IntegerField(blank=True, null=True)),
                ('loser_rank', models.IntegerField(blank=True, null=True)),
                ('loser_rank_points', models.IntegerField(blank=True, null=True)),
                ('w_elo', models.IntegerField(blank=True, null=True)),
                ('l_elo', models.IntegerField(blank=True, null=True)),
                ('w_elo_ts', models.IntegerField(blank=True, null=True)),
                ('l_elo_ts', models.IntegerField(blank=True, null=True)),
                ('l_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l_match', to='tennis.player')),
                ('tourney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.tourney')),
                ('w_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_match', to='tennis.player')),
            ],
        ),
    ]
