version: '3.7'

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'tennis'
      MYSQL_USER: 'vaino'
      MYSQL_PASSWORD: 'abcde'
      MYSQL_ROOT_PASSWORD: 'abcde'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
